name: MegaLinter

on:
  pull_request:
    branches: [main, master]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # For posting comments (optional, depending on config)
      issues: write        # For posting comments (optional)
      statuses: write      # For setting commit status

    steps:
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0 # Reviewdog/MegaLinter needs history

      - name: MegaLinter
        id: ml
        uses: oxsecurity/megalinter@ef3e84b8b836d76db562d0f3ed7da61e8fd538bc # v9.6.0
        env:
          # VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'workflow_dispatch' }} # Validates all source when push on main, else just the git diff with main.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Mapped to .mega-linter.yml by default, but can ideally force it here
          MEGALINTER_CONFIG: .mega-linter.yml

      - name: Archive Production Artifacts
        if: success() || failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
            mega-linter.log
